<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <AssemblyName>PHD2Insight.UI</AssemblyName>
    <RootNamespace>PHD2Insight.UI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>

    <PackageReference Include="Avalonia" Version="11.2.3" />

    <PackageReference Include="Avalonia.Desktop" Version="11.2.3" />

    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.3" />

    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />

    <PackageReference Include="Tmds.DBus.Protocol" Version="0.21.3" />

  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PHD2Insight.Analysis\PHD2Insight.Analysis.csproj" />
    <ProjectReference Include="..\PHD2Insight.Parser\PHD2Insight.Parser.csproj" />
  </ItemGroup>

</Project>